language: java
dist: trusty
jdk: openjdk9

addons:
  sonarcloud:
    organization: "microconfig"
    token: 73371217f9b049ece1f4ba72f70212e6fcdbaa52

script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
  - ./gradlew sonarqube